FEATURE_DETAILS = {'AC_LOSSES': {'text': 'AC Losses', 'type': 'string'},
 'AJB_DETAILS': {'text': 'AJB Details', 'type': 'string'},
 'AJB_POWER': {'text': 'Ajb Power', 'type': 'string'},
 'AMBIENT_TEMPERATURE': {'text': 'Ambient Temperature', 'type': 'string'},
 'ANALYTICS_DASHBOARD': {'text': 'Analytics Dashboard', 'type': 'string'},
 'CLEANING': {'text': 'Cleaning', 'type': 'string'},
 'CO2': {'text': 'CO2', 'type': 'string'},
 'CONVERSION_LOSSES': {'text': 'Conversion Losses', 'type': 'string'},
 'CUF': {'text': 'CUF', 'type': 'string'},
 'CURRENT_POWER': {'text': 'Current Power', 'type': 'string'},
 'DAILY': {'text': 'Daily', 'type': 'string'},
 'DC_LOSSES': {'text': 'DC Losses', 'type': 'string'},
 'DEVICE_DETAILS': {'text': 'Device Details', 'type': 'string'},
 'EMAIL_NOTIFICATIONS': {'text': 'Email Notifications', 'type': 'string'},
 'ENERGY_GENERATION': {'text': 'Energy Generation', 'type': 'string'},
 'EQUIPMENT_AVAILABILITY': {'text': 'Equipment Availability',
  'type': 'string'},
 'GATEWAY_ALERTS': {'text': 'Gateway Alerts', 'type': 'string'},
 'GATEWAY_DETAILS': {'text': 'Gateway Details', 'type': 'string'},
 'GRID_AVAILABILITY': {'text': 'Grid Availability', 'type': 'string'},
 'GROUP_POWER_CHART': {'text': 'Group Power Chart', 'type': 'string'},
 'HOMES_POWERED': {'text': 'Homes Powered', 'type': 'string'},
 'INSOLATION': {'text': 'Insolation', 'type': 'string'},
 'INVERTERS_INFORMATION': {'text': 'Inverters Information',
  'type': 'string'},
 'INVERTER_ALERTS': {'text': 'Inverter Alerts', 'type': 'string'},
 'INVERTER_COMPARISON': {'text': 'Inverter Comparison', 'type': 'string'},
 'INVERTER_ENERGY': {'text': 'Inverter Energy', 'type': 'string'},
 'INVERTER_POWER': {'text': 'Inverter Power', 'type': 'string'},
 'IRRADIATION_CHART': {'text': 'Irradiation Chart', 'type': 'string'},
 'LOGO': {'text': 'Logo', 'type': 'string'},
 'METER_ALERTS': {'text': 'Meter Alerts', 'type': 'string'},
 'METER_DETAILS': {'text': 'Meter Details', 'type': 'string'},
 'METER_GENERATION': {'text': 'Meter Generation', 'type': 'string'},
 'METER_POWER': {'text': 'Meter Power', 'type': 'string'},
 'MODULE_TEMPERATURE': {'text': 'Module Temperature', 'type': 'bar'},
 'MONTHLY': {'text': 'Monthly', 'type': 'string'},
 'MPPT_COMPARISON': {'text': 'Mppt Comparison', 'type': 'string'},
 'OPEN_TICKETS': {'text': 'Open Tickets', 'type': 'string'},
 'PANELS_INFORMATION': {'text': 'Panels Information', 'type': 'string'},
 'PEAK_POWER': {'text': 'Peak Power', 'type': 'string'},
 'PLANTS_OVERVIEW': {'text': 'Plants Overview', 'type': 'string'},
 'POWER_CHART': {'text': 'Power Chart', 'type': 'string'},
 'PPA': {'text': 'PPA', 'type': 'string'},
 'PR': {'text': 'Performance Ratio', 'type': 'bar'},
 'PREDICTED_ENERGY_TILL_NOW': {'text': 'Predicted Energy Till Now',
  'type': 'string'},
 'PREDICTION_DEVIATION': {'text': 'Prediction Deviation', 'type': 'string'},
 'PREDICTION_TIMESERIES': {'text': 'Prediction Timeseries',
  'type': 'string'},
 'PREDICTION_TODAY': {'text': 'Prediction Today', 'type': 'string'},
 'PVSYST_CUF': {'text': 'Pvsyst Cuf', 'type': 'string'},
 'PVSYST_GENERATION': {'text': 'Pvsyst Generation', 'type': 'string'},
 'PVSYST_PR': {'text': 'Pvsyst Pr', 'type': 'string'},
 'PVSYST_SY': {'text': 'Pvsyst Sy', 'type': 'string'},
 'SMB_ALERTS': {'text': 'SMB Alerts', 'type': 'string'},
 'SMB_COMPARISON': {'text': 'SMB Comparison', 'type': 'string'},
 'SMS_NOTIFICATIONS': {'text': 'SMS Notifications', 'type': 'string'},
 'SOILING_LOSSES': {'text': 'Soiling Losses', 'type': 'string'},
 'SY': {'text': 'Specific Yield', 'type': 'string'},
 'TOTAL_CAPACITY': {'text': 'Total Capacity', 'type': 'string'},
 'TOTAL_ENERGY': {'text': 'Total Energy', 'type': 'string'},
 'TOTAL_SITES': {'text': 'Total Sites', 'type': 'string'},
 'TREES_PLANTED': {'text': 'Trees Planted', 'type': 'string'},
 'WEATHER_STATION_ALERTS': {'text': 'Weather Station Alerts',
  'type': 'string'},
 'WEEKLY_GENERATION': {'text': 'Weekly Generation', 'type': 'string'},
 'WIND_SPEED': {'text': 'Wind Speed', 'type': 'string'},
 'YEARLY': {'text': 'Yearly', 'type': 'string'},
 'INVERTERS_STATUS': {'text': 'Inverter Status', 'type': 'string'},
 'DATA_LOGGERS_STATUS': {'text': 'Data Logger Status', 'type': 'string'},
 'IRRADIANCE': {'text': 'Irradiance', 'type': 'string'}}